--------------------------------------------------------
--  Fichier créé - mercredi-décembre-30-2020   
--------------------------------------------------------
DROP TABLE "INES"."PARKINGS" cascade constraints;
DROP TABLE "INES"."VEHICULES" cascade constraints;
--------------------------------------------------------
--  DDL for Table PARKINGS
--------------------------------------------------------

  CREATE TABLE "INES"."PARKINGS" 
   (	"REFF" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(20 BYTE), 
	"NB_PLACE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table VEHICULES
--------------------------------------------------------

  CREATE TABLE "INES"."VEHICULES" 
   (	"ID" NUMBER, 
	"MATRICULE" VARCHAR2(20 BYTE), 
	"MARQUE" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"DATE_MISE" VARCHAR2(20 BYTE), 
	"ID_PARKING" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into INES.PARKINGS
SET DEFINE OFF;
Insert into INES.PARKINGS (REFF,NOM,ADRESSE,NB_PLACE) values ('1','Parking1','Ariana','30');
Insert into INES.PARKINGS (REFF,NOM,ADRESSE,NB_PLACE) values ('2','Parking2','Ariana','30');
Insert into INES.PARKINGS (REFF,NOM,ADRESSE,NB_PLACE) values ('3','Parking3','Ariana','30');
Insert into INES.PARKINGS (REFF,NOM,ADRESSE,NB_PLACE) values ('4','Parking4','Ariana','30');
Insert into INES.PARKINGS (REFF,NOM,ADRESSE,NB_PLACE) values ('5','Parking5','Ariana','30');
Insert into INES.PARKINGS (REFF,NOM,ADRESSE,NB_PLACE) values ('6','Parking6','Ariana','50');
Insert into INES.PARKINGS (REFF,NOM,ADRESSE,NB_PLACE) values ('7','Parking7','Ariana','50');
REM INSERTING into INES.VEHICULES
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PARKINGS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "INES"."PARKINGS_PK" ON "INES"."PARKINGS" ("REFF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index VEHICULES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "INES"."VEHICULES_PK" ON "INES"."VEHICULES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PARKINGS
--------------------------------------------------------

  ALTER TABLE "INES"."PARKINGS" ADD CONSTRAINT "PARKINGS_PK" PRIMARY KEY ("REFF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "INES"."PARKINGS" MODIFY ("REFF" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VEHICULES
--------------------------------------------------------

  ALTER TABLE "INES"."VEHICULES" ADD CONSTRAINT "VEHICULES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "INES"."VEHICULES" MODIFY ("ID" NOT NULL ENABLE);
